services:
  mysql:
    image: mysql:8.0
    container_name: stepbookstep-mysql-local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: stepbookstep
      MYSQL_USER: stepbookstep
      MYSQL_PASSWORD: root1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_local_data:/var/lib/mysql
    networks:
      - backend-bridge

  redis:
    image: redis:7.2.5
    container_name: stepbookstep-redis-local
    ports:
      - "6379:6379"
    networks:
      - backend-bridge

volumes:
  mysql_local_data:

networks:
  backend-bridge:
    driver: bridge