spring:
  application:
    name: stepbookstep

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# ??? API ?? ??
aladin:
  api:
    url: https://www.aladin.co.kr/ttb/api
    ttb-key: ${ALADIN_API_KEY:default-key}
    output: json
    version: "20131101"

# ?? ?? ??
server:
  port: 8080

# ?? ?? ??
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.zaxxer.hikari: INFO

# Actuator ??
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always  # Health ?? ?? ??