services:
  stepbookstep-app:
    image: stepbookstep/server:latest
    container_name: stepbookstep-dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  mysql:
    image: mysql:8.0
    container_name: stepbookstep-mysql
    volumes:
      - mysql_dev_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  redis:
    image: redis:7.2.5
    container_name: stepbookstep-redis
    ports:
      - '6379:6379'

volumes:
  mysql_dev_data:
    driver: local

networks:
  backend-bridge:
    driver: bridge

