services:
  mysql:
    image: mysql:8.0
    container_name: stepbookstep-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_local_data:/var/lib/mysql
    networks:
      - backend-bridge

  redis:
    image: redis:7.2.5
    container_name: stepbookstep-redis
    ports:
      - "6379:6379"
    networks:
      - backend-bridge

volumes:
  mysql_local_data:
    driver: local

networks:
  backend-bridge:
    driver: bridge