name: CI - Build & Test (Local Only)

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Generate application.yml for Test
        run: |
          mkdir -p src/main/resources
          mkdir -p src/test/resources
          cat <<EOF > src/main/resources/application.yml
          spring:
            datasource:
              url: jdbc:h2:mem:testdb
              driver-class-name: org.h2.Driver

          stepbookstep:
            jwt:
              key: "${{ secrets.JWT_KEY }}"
              access:
                expiration: 3600000
              refresh:
                expiration: 86400000

          kakao:
            client-id: test
            client-secret: test
            redirect-uri: http://localhost
            admin-key: test
          EOF
          cp src/main/resources/application.yml src/test/resources/application.yml

      - name: Build project
        run: ./gradlew clean build -x test

      - name: Run tests
        run: ./gradlew test


