name: CI/CD Dev

on:
  push:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout source
        uses: actions/checkout@v4

      - name: 2. Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: 3. application.yml 파일 설정
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: 4. Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      - name: 5. Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 6. Build JAR
        run: ./gradlew clean build -x test

      - name: 7. Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: 8. Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/server:latest

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout source
        uses: actions/checkout@v4

      - name: 2. Create .env file
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: 2-1. .env 파일 EC2에 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ".env"
          target: "/home/ubuntu/stepbookstep-dev/docker/"

      - name: Check docker-compose.dev.yml exists
        run: ls -al ./docker/

      - name: 3. docker-compose.yml 전달
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./docker/docker-compose.dev.yml"
          target: "/home/ubuntu/stepbookstep-dev/"  # <= 경로 일치시킴

      - name: 4. SSH to Dev Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          command_timeout: 15m
          script: |
            cd /home/ubuntu/stepbookstep-dev/docker/
            docker pull ${{ secrets.DOCKER_USERNAME }}/server:latest
            docker compose -f docker-compose.dev.yml down
            docker compose -f docker-compose.dev.yml up -d
